### ISSUE TITLE
Implement Half class

### ISSUE THREAD

**Issue by utilForever** [utilForever/CubbyDNN#17]
C++ don't support [Half-precision floating-point format](https://en.wikipedia.org/wiki/Half-precision_floating-point_format).
Most deep learning frameworks support this type.
So, we have to implement Half class to support it.

**Comment by Ravenwater** [comment]
There were two key reasons why I wanted to join your team: 1- a clean C++17 implementation of a DL framework was attractive, and 2- to make certain that your library was able to be used as an exploration for new number systems as that is where all the perf per Watt innovation is going to come from.

The github.com/stillwater-sc/universal library was set up to provide a collection of parameterized number systems. We currently support arbitrary floats and posits. We are working on bfloats and the FAIR logarithmic number system.

I would kindly offer that you pull in that library, and use it to deliver fp16 (afloat<16,5> for arbitrary float of size 16 bits with 5 exponent bits)
