### ISSUE TITLE
What is the role of Tensor-related classes?

### ISSUE THREAD

**Issue by utilForever** [utilForever/CubbyDNN#22]
There are many classes related to Tensor in this framework.
(Tensor/TensorData/TensorInfo/TensorObject/TensorShape)
I would like to let you know the role of each class. If you like, you can write in Korean.

**Comment by Ravenwater** [comment]
simple UML diagram would likely do. 

from a type perspective, the fact that tensors can be chained is going to be the tricky part. So tensor compositions such as Kronecker products, Trace-Singh, etc. should be expressible.

Secondly, automatic differentiation is required as well to support the back propagation phase. 

That are two requirements that are none trivial, especially when there is multi-precision tensors at play.

**Comment by utilForever** [comment]
@Ravenwater Oh, I asked the question to @jwkim98.
I've heard answer through Facebook messenger, so I'll close the issue. Thanks. 🎉

**Comment by Ravenwater** [comment]
:-) no problem:

Here is a good link on the AD part: https://arxiv.org/abs/1711.01348

**Comment by utilForever** [comment]
@Ravenwater Can you reply this? https://gist.github.com/utilForever/1e0a93263ff5d52ae35304906e9c980a
