### ISSUE TITLE
Adding Universal number system library to project

### ISSUE THREAD

**Issue by jwkim98** [utilForever/CubbyDNN#26]
Attatch new library for bFloat16 and posit number systems
https://github.com/stillwater-sc/universal

Planning to make use of BLAS implementation from this library for CPU implementation.
POSIT numbers and bFloat16 will be converted to IEEE754 form for GPU implementation.

As new library assumes support of AVX2 instructions, We are going to assume support of AVX2 as well

**Comment by Ravenwater** [comment]
the raw universal library does not contain a BLAS implementation, just the number system arithmetic. 

The BLAS functionality is done in reproducible form in HPR-BLAS (https://github.com/stillwater-sc/hpr-blas) and in 'fast' form in MTL4/5. HPR-BLAS depends on the vector and matrix data structures of MTL to gain hierarchical, blocked, and sparse matrix/vector expressions.

The MTL5 roadmap includes a full tensor math engine.

The question is whether or not you want to pull in MTL or not.

I would say that at this juncture we may just want to implement a non-MTL matvec and matmul, but use the same C++ interface as HPR-BLAS. That way we can move over smoothly in the future if that is merited.

**Comment by jwkim98** [comment]
@Ravenwater 
Agreed.
We will just use posit number definitions from ./posit directory.
But I'm really looking forward to apply optimized BLAS implementation for posit number systems. 
We will consider adding HPR-BLAS later as you suggested when we finish implementing basic functionalities.

**Comment by Ravenwater** [comment]
How were you planning to pull the lib in? via a download into a vendor dir, or revision cache?

The only thing you would need is the posit directory, and add ```include <posit>``` to the source. There are some config bits that we'll want to use, but the default config will work out of the box.

**Comment by jwkim98** [comment]
@Ravenwater 
Yes that's exactly what I meant. Sorry for misunderstandings

**Comment by Ravenwater** [comment]
The 'structure' of the library is that each number system gets its own subdirectory off universal, so universal/posit, universal/afloat, universal/valid, etc., and they will have a C++-style system header that brings everything in, as in `include <posit>`, `include <afloat>`, etc.. After that you will have a new arithmetic that is completely type driven. 

From there, you typically use this pattern:
```
using Scalar = sw::unum::afloat<8,2>;
```
as a mechanism to inject that arithmetic into the environment, assuming of course that the compute is parameterized by `Scalar`.

**Comment by Ravenwater** [comment]
@jwkim98 just released fast posit<8,0> support:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/unum-computing/ySusEOgOxRk
```
Processor: Intel Core i7-7500 CPU @ 2.70GHz, 2 cores, 4 threads, 15W mobile processor
Memory   : 16GB
System   : 64-bit Windows 10 Pro, Version 1803, x64-based processor, OS build 17134.165
```
```
Fast specialization posit<4,0> configuration performance tests
Performance Report: posit<4,0>
Conversion int  :  99 MPOPS
Conversion ieee :   2 MPOPS
Prefix          : 622 MPOPS
Postfix         : 624 MPOPS
Negation        : 884 MPOPS
Addition        :   1 GPOPS
Subtraction     : 938 MPOPS
Multiplication  : 900 MPOPS
Division        : 760 MPOPS
Square Root     : 378 MPOPS
```
```
Performance Report: posit<8,0>
Conversion int  : 326 MPOPS
Conversion ieee :   2 MPOPS
Prefix          : 914 MPOPS
Postfix         :   1 GPOPS
Negation        :   1 GPOPS
Addition        :  96 MPOPS
Subtraction     :  88 MPOPS
Multiplication  : 168 MPOPS
Division        :  63 MPOPS
Square Root     :   1 GPOPS
```

**Comment by jwkim98** [comment]
@Ravenwater 
Thank you for notifying me and your hard work.

I'm currently designing implementation strategies and doing some research before moving on to the code. It's nice to hear that you released new support for posits.

I'll check for details as soon as possible
