### ISSUE TITLE
Discussion about Abstraction

### ISSUE THREAD

**Issue by Yoogeonhui** [utilForever/CubbyDNN#31]
- Modeling(Sequential models and nonsequential models)
- Training

**Comment by Ravenwater** [comment]
How is the library design going? I haven't seen much activity. We have been working with the TVM/VTA folks and we will have a VTA hardware accelerator in the style of the Google TPU. If this library could directly drive the VTA-style hardware you would have an amazing research and teaching vehicle.

**Comment by jwkim98** [comment]
@Ravenwater
We've implemented asynchronous layer for graph execution and testing it.
From now, @utilforever will work on CubbyMath, which can process matrices with efficient way
(Which has similar role with numpy in python). Cubbymath will be added as submodule to CubbyDNN and CubbyDNN will use its implementation.
I guess your suggestion can be considered in implementation of CubbyMath.

> How is the library design going? I haven't seen much activity. We have been working with the TVM/VTA folks and we will have a VTA hardware accelerator in the style of the Google TPU. If this library could directly drive the VTA-style hardware you would have an amazing research and teaching vehicle.
