### ISSUE TITLE
Build is not working, need dependencies

### ISSUE THREAD

**Issue by Ravenwater** [utilForever/CubbyDNN#7]
Trying to build DNN I ran into dependency issues:

Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.17134.
CMake Error at CMakeLists.txt:39 (add_subdirectory):
  The source directory

    C:/Users/tomtz/Documents/dev/clones/CubbyDNN/Libraries/googletest

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:42 (add_subdirectory):
  The source directory

    C:/Users/tomtz/Documents/dev/clones/CubbyDNN/Libraries/googlebenchmark

  does not contain a CMakeLists.txt file.

Configuring incomplete, errors occurred!
See also "C:/Users/tomtz/Documents/dev/clones/CubbyDNN/build/CMakeFiles/CMakeOutput.log".

**Comment by Ravenwater** [comment]
In the README it should state that you need to recurse:
```
git clone --recurse-submodules https://github.com/utilForever/CubbyDNN
```

**Comment by jwkim98** [comment]
Thank you for giving us comments. 
I'm facing dependency issues going on my Ubuntu linux laptop.
I'll fix that problem as soon as I can.
