### ISSUE TITLE
use standard C++ rules for file naming

### ISSUE THREAD

**Issue by Ravenwater** [utilForever/CubbyDNN#8]
include files use a .h extension, which incorrectly indicates it is a C include file.

Please use .hpp and .cpp file extensions for C++ code.

**Comment by jwkim98** [comment]
I think .h extension for header files was set by default on my IDE.
 I'll use .hpp instead from the next commit

**Comment by Ravenwater** [comment]
I would appreciate it very much.  For C++ we always follow the BOOST structure, as that was the path to getting included in the C++ standard. We do have embedded environments where a .h file gets interpreted as a C header file, and to make it clear in the large code base what is C code and what is proper C++ code, the industry has used the .h/.c and .hpp/.cpp designations to make it easy to understand, visually pleasing, and phonetically consistent.

**Comment by utilForever** [comment]
@Ravenwater We apply this rules.
